export const CacheRooms: any = new Map()
export const WAITING_ROOM = 'waiting_room'

export const gameVariantsDefault = [
  {
    id: 1,
    size: "small",
    difficulty: "easy",
    roomId: "",
    firstPlayerSocketId: "",
    width: 14,
    height: 21,
    bombsCount: 44,
    timerStartValue: 30,
  },
  {
    id: 2,
    size: "small",
    difficulty: "normal",
    roomId: "",
    firstPlayerSocketId: "",
    width: 14,
    height: 21,
    bombsCount: 58,
    timerStartValue: 35,
  },
  {
    id: 3,
    size: "small",
    difficulty: "hard",
    roomId: "",
    firstPlayerSocketId: "",
    width: 14,
    height: 21,
    bombsCount: 73,
    timerStartValue: 40,
  },
  {
    id: 4,
    size: "medium",
    difficulty: "easy",
    roomId: "",
    firstPlayerSocketId: "",
    width: 20,
    height: 30,
    bombsCount: 90,
    timerStartValue: 40,
  },
  {
    id: 5,
    size: "medium",
    difficulty: "normal",
    roomId: "",
    firstPlayerSocketId: "",
    width: 20,
    height: 30,
    bombsCount: 120,
    timerStartValue: 45,
  },
  {
    id: 6,
    size: "medium",
    difficulty: "hard",
    roomId: "",
    firstPlayerSocketId: "",
    width: 20,
    height: 30,
    bombsCount: 150,
    timerStartValue: 50,
  },
  {
    id: 7,
    size: "large",
    difficulty: "easy",
    roomId: "",
    firstPlayerSocketId: "",
    width: 26,
    height: 39,
    bombsCount: 151,
    timerStartValue: 50,
  },
  {
    id: 8,
    size: "large",
    difficulty: "normal",
    roomId: "",
    firstPlayerSocketId: "",
    width: 26,
    height: 39,
    bombsCount: 202,
    timerStartValue: 55,
  },
  {
    id: 9,
    size: "large",
    difficulty: "hard",
    roomId: "",
    firstPlayerSocketId: "",
    width: 26,
    height: 39,
    bombsCount: 253,
    timerStartValue: 60,
  },
]
export const cacheGameVariants: any = [...gameVariantsDefault]