import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.scss";
import {SocketProvider} from "../../components/providers/socket-provider";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning={true} lang="en">
    <body className={inter.className}>
    <SocketProvider>
      <main>
        {children}
      </main>
    </SocketProvider>
    </body>
    </html>
  );
}

